version: '3.5'

services:

  nginx:
    container_name: "nginx"
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./app/media_files:/usr/share/nginx/html/static/media_files
    networks:
      - custom

  web:
    container_name: "web"
    build: ./app

    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - custom
    depends_on:
      - db


  db:
    container_name: "db"
    image: postgres:13-alpine
    volumes:
      - ./db_dev/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=twitter_clone
    env_file:
      - ./.env.dev.db
    ports:
      - '5432:5432'
    networks:
      - custom


volumes:
  media_files:
    driver: local
  db_dev:
    name: db_dev

networks:
  custom:
    driver: bridge
