global:
  scrape_interval:     3s

  external_labels:
    monitor: 'twitter-clone'


scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'twitter-clone'

    dns_sd_configs:
      - names: ['web']
        port: 8000
        type: A
        refresh_interval: 5s
