"""Init migration

Revision ID: 76f06bfca28b
Revises: efec93013707
Create Date: 2023-09-07 20:46:07.397612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f06bfca28b'
down_revision = 'efec93013707'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
