"""Init migration

Revision ID: a73be91d7bc5
Revises: 76f06bfca28b
Create Date: 2023-09-08 13:08:03.565479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73be91d7bc5'
down_revision = '76f06bfca28b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
